### ISSUE TITLE
Non-select queries don't show feedback

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/judge-sql#89]
- [ ] https://naos.ugent.be/en/submissions/981627/ in #87 (review this PR)
![image](https://user-images.githubusercontent.com/56451049/134133245-41806f28-e858-48e3-932a-c554477c8817.png)

Should be
![image](https://user-images.githubusercontent.com/56451049/134133282-4690150d-3ba6-426a-a35b-ba45d95eefbc.png)

**Comment by inteon** [comment]
fixed in #91
